# ESO → Secret minio (ns minio) — Bitnami existingSecret + bucket-policy Job
# Vault: secret/cinehome/minio
# Keys khớp Bitnami MinIO: root-user, root-password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
  labels:
    app.kubernetes.io/part-of: cinehome
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio
    creationPolicy: Owner
  data:
    - secretKey: root-user
      remoteRef:
        key: cinehome/minio
        property: rootUser
    - secretKey: root-password
      remoteRef:
        key: cinehome/minio
        property: rootPassword
