apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cinehome-mesh
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: cinehome
    app.kubernetes.io/component: mesh
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: cinehome-platform
  source:
    repoURL: https://github.com/kevinram164/movie-web.git
    targetRevision: main
    path: deploy/mesh
  destination:
    server: https://kubernetes.default.svc
    namespace: npd-movie
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    automated:
      prune: false
      selfHeal: true
