apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cinehome-routes
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: cinehome
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: cinehome-platform
  source:
    repoURL: https://github.com/kevinram164/movie-web.git
    targetRevision: main
    path: deploy/routes
    directory:
      include: cinehome-route.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: npd-movie
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-routes
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: cinehome
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: cinehome-platform
  source:
    repoURL: https://github.com/kevinram164/movie-web.git
    targetRevision: main
    path: deploy/routes
    directory:
      include: minio-routes.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
