# StorageClass NFS CSI — lab NPD (10.100.1.180)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    cinehome/environment: dev-ocp
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.100.1.180"
  share: "/shares/registry"
  subDir: "${pvc.metadata.namespace}/${pvc.metadata.name}"
  # Lab: Harbor Postgres (UID 999) cần ghi pgdata — mặc định CSI là 0750 (root) → Permission denied
  mountPermissions: "0777"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - hard
  - timeo=600
