{{- range $name := list "movie-web" "movie-api" "media-worker" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: cinehome
    app.kubernetes.io/component: {{ $name }}
{{- end }}
