# Image tags — CI (cinehomePipeline / Kaniko) cập nhật trên nhánh main
movieApi:
  image:
    repository: harbor-platform.apps.ocp01.npd.co/movie-web/movie-api
    tag: 06a17ba
    pullPolicy: Always

movieWeb:
  image:
    repository: harbor-platform.apps.ocp01.npd.co/movie-web/movie-web
    tag: dfabe7d
    pullPolicy: Always

mediaWorker:
  image:
    repository: harbor-platform.apps.ocp01.npd.co/movie-web/media-worker
    tag: dfabe7d
    pullPolicy: Always
