# Observability — Coroot + OTEL + Linkerd (dev-ocp)
# Sync sau platform, trước banking app
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-app-of-apps-dev-ocp
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: phase9-gitops
    cinehome/environment: dev-ocp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: cinehome-platform
  source:
    repoURL: https://github.com/kevinram164/movie-web.git
    targetRevision: main
    path: phase9-gitops-platform/gitops-platform/applications/observability
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
