apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - harbor-route.yaml
  - jenkins-route.yaml
  - vault-route.yaml
  - argocd-route.yaml
  - coroot-route.yaml
  - linkerd-viz-route.yaml
  # CineHome + MinIO routes: deploy/routes (cinehome-app-of-apps)
